
export const START_QUIZ = 'START_QUIZ';
export const START_QUIZ_SUCCESS = 'START_QUIZ_SUCCESS';
export const START_QUIZ_ERROR = 'START_QUIZ_ERROR';

export const NEXT_QUESTION = 'NEXT_QUESTION';

export const SEND_ANSWER = 'SEND_ANSWER';
export const SEND_ANSWER_SUCCESS = 'SEND_ANSWER_SUCCESS';
export const SEND_ANSWER_ERROR = 'SEND_ANSWER_ERROR';


